package sdjwt

// Tests in this file verify the sdjwt package against test vectors extracted
// from the OpenWallet Foundation (OWF) Labs SD-JWT reference implementation:
//
//	https://github.com/openwallet-foundation-labs/sd-jwt-python
//
// The test vectors were generated by running the reference implementation's
// Issuer → Holder → Verifier flow for each of its test cases and examples,
// then capturing the presentation tokens, issuer keys, and expected verified
// claims. See testdata/extract_testcases.py for the extraction script and
// testdata/Dockerfile for the Docker build that runs it.

import (
	"crypto"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"
)

type owfTestCase struct {
	Name                   string         `json:"name"`
	Source                 string         `json:"source"`
	SerializationFormat    string         `json:"serialization_format"`
	SignAlg                string         `json:"sign_alg"`
	KeyBinding             bool           `json:"key_binding"`
	KBNonce                string         `json:"kb_nonce"`
	KBAud                  string         `json:"kb_aud"`
	IssuerPublicKeyJWK     map[string]any `json:"issuer_public_key_jwk"`
	HolderPublicKeyJWK     map[string]any `json:"holder_public_key_jwk"`
	SDJWTPresentation      string         `json:"sd_jwt_presentation"`
	ExpectedVerifiedClaims map[string]any `json:"expected_verified_claims"`
	IAT                    int64          `json:"iat"`
	EXP                    int64          `json:"exp"`
}

func loadOWFTestCases(t *testing.T) []owfTestCase {
	t.Helper()
	data, err := os.ReadFile("testdata/owf_reference_testcases.json")
	if err != nil {
		t.Fatalf("read test fixture: %v", err)
	}
	var cases []owfTestCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatalf("parse test fixture: %v", err)
	}
	return cases
}

// parsePublicKeyFromJWK converts a JWK map to a crypto.PublicKey using the
// same parsing functions that Verify uses internally for cnf.jwk.
func parsePublicKeyFromJWK(jwk map[string]any) (crypto.PublicKey, error) {
	kty, _ := jwk["kty"].(string)
	switch kty {
	case "EC":
		return parseECPublicKey(jwk)
	case "RSA":
		return parseRSAPublicKey(jwk)
	default:
		return nil, fmt.Errorf("unsupported key type in test fixture: %q", kty)
	}
}

func TestOWFReference(t *testing.T) {
	cases := loadOWFTestCases(t)

	for _, tc := range cases {
		tc := tc
		name := tc.Source + "/" + tc.Name
		t.Run(name, func(t *testing.T) {
			if tc.SerializationFormat != "compact" {
				t.Skipf("JSON serialization not supported (format=%s)", tc.SerializationFormat)
			}

			key, err := parsePublicKeyFromJWK(tc.IssuerPublicKeyJWK)
			if err != nil {
				t.Fatalf("parse issuer key: %v", err)
			}

			// Use a fixed time between iat and exp.
			verifyTime := time.Unix(tc.IAT+1, 0)

			opts := []Option{WithTime(verifyTime)}

			if tc.KeyBinding {
				opts = append(opts, WithKeyBinding(tc.KBNonce, tc.KBAud))
			}

			claims, err := Verify(tc.SDJWTPresentation, key, opts...)
			if err != nil {
				t.Fatalf("Verify failed: %v", err)
			}

			// Compare payload against expected claims.
			gotJSON, err := json.Marshal(claims.Payload)
			if err != nil {
				t.Fatalf("marshal got: %v", err)
			}
			wantJSON, err := json.Marshal(tc.ExpectedVerifiedClaims)
			if err != nil {
				t.Fatalf("marshal want: %v", err)
			}

			// Unmarshal both to normalized map[string]any for comparison.
			var got, want any
			if err := json.Unmarshal(gotJSON, &got); err != nil {
				t.Fatalf("re-unmarshal got: %v", err)
			}
			if err := json.Unmarshal(wantJSON, &want); err != nil {
				t.Fatalf("re-unmarshal want: %v", err)
			}

			if !jsonEqual(got, want) {
				t.Errorf("claims mismatch\ngot:  %s\nwant: %s", gotJSON, wantJSON)
			}
		})
	}
}

// jsonEqual performs a deep comparison of two JSON-decoded values,
// treating integer and float representations of the same number as equal.
func jsonEqual(a, b any) bool {
	switch av := a.(type) {
	case map[string]any:
		bv, ok := b.(map[string]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for k, va := range av {
			vb, ok := bv[k]
			if !ok || !jsonEqual(va, vb) {
				return false
			}
		}
		return true
	case []any:
		bv, ok := b.([]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if !jsonEqual(av[i], bv[i]) {
				return false
			}
		}
		return true
	case float64:
		bv, ok := b.(float64)
		return ok && av == bv
	case string:
		bv, ok := b.(string)
		return ok && av == bv
	case bool:
		bv, ok := b.(bool)
		return ok && av == bv
	case nil:
		return b == nil
	default:
		return false
	}
}
